[package]
name = "verify-archive"
version = "0.1.0"
edition = "2018"

repository = "https://github.com/reckenrode/verify-archive"
categories = ["command-line-utilities"]
keywords = ["backups"]
license = "GPL-3.0-only"
readme = "README.md"

authors = ["Randy Eckenrode <randy@largeandhighquality.com>"]
description = "Compare Backblaze backup archives to the local filesystem for discrepancies"

[dependencies]
async-stream = "0.3.2"
blake3 = "1"
futures-core = "0.3"
futures-util = "0.3"
tokio = { version = "1", features = ["full"] }
zip = "0.5.13"

[dev-dependencies]
tempfile = "3.2"
